# Передмова {.unnumbered}

Зараз маємо такий план підручника

## Вступ

## Розділ І. Якісні методи психологічного дослідження.

### 1.1. Фокус–групи

### 1.2. Глибинне інтерв’ю

## Розділ ІІ. Кількісні методи психологічного дослідження.

## 2.1. Міждисциплінарні методи

### 2.1.1. Методи соціології

### 2.1.2. Методи маркетингу

### 2.1.3. Методи політтехнології

### 2.1.4. Методи політології

## 2.2. Дослідження преференцій

### 2.2.1. Карти сприйняття

### 2.2.2. Конджойнт-аналіз

## 2.3. Методи вивчення особистості політика (портрет)

### 2.3.1. Опосередковані (дистанційні) методи

### 2.3.2. Спостереження

### 2.3.3. Аналіз текстів, виступів

### 2.3.4. Біографічний метод

## 2.4. Методи дослідження вибору

### 2.4.1. Експерименти

### 2.4.2. Конджойнт-аналіз

## 2.5. Методи вивчення цільової аудиторії

## Розділ ІІІ. Кількісно-якісні методи.

### 3.1. Детермінанти індивідуальної політичної поведінки

### 3.1.1. Q-методологія

### 3.1.2. Психосемантичні методи

### 3.1.3. Вивчення установок

### 3.1.4. Вивчення соціально-психологічних механізмів впливу

### 3.2. Контент-аналіз документів

### 3.3. Аналіз соціальних мереж

### 3.4. Агентне моделювання

### 3.5. Методи з використанням штучного інтелекту
