# Вступ

Проведення дослідження - це багатогранний процес, який потребує значного обсягу знань і вмінь. На початку своєї дослідницької кар'єри мало хто має ці знання і досвід. Тому корисно розпочати з завдань, які на початковому етапі не вимагають такого обсягу компетентності. Наприклад, можна проаналізувати дані з вдалого порівняльного дослідження. Хоча такі дані можуть не бути бездоганними, потенційна критика ймовірно не викличе значних турбот, оскільки відповідальність за оригінальне дослідження лежить на інших людях. Проте цей підхід дає дослідникові можливість вдосконалити свої аналітичні здібності через роботу з прикладними наборами даних, отримуючи при цьому уявлення про методологічні тонкощі та найкращі практики. Крім того, успішна робота з існуючими даними може послужити вихідною точкою для розробки стратегій отримання вищої якості даних у майбутніх дослідженнях. Принаймні, така практика допомагає налагоджувати критичне мислення щодо нових методологій, запропонованих іншими, сприяючи готовності спілкуватися з еміргентними дослідницькими парадигмами.

За цим посиланням знаходиться портал даних Європейського Соціального Дослідження: <https://ess.sikt.no/>
